// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcF2r_PFOX-FNq9FbOw2fZrp87fzoaeZI',
    appId: '1:260805929748:web:0f7254f07451a8bc097001',
    messagingSenderId: '260805929748',
    projectId: 'rentalcar-ba0ca',
    authDomain: 'rentalcar-ba0ca.firebaseapp.com',
    storageBucket: 'rentalcar-ba0ca.appspot.com',
    measurementId: 'G-KFLVKGC8KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzNRcAiLnYI8sXPHzjsAIx-PihonCEy0o',
    appId: '1:260805929748:android:f2b765829bc7499a097001',
    messagingSenderId: '260805929748',
    projectId: 'rentalcar-ba0ca',
    storageBucket: 'rentalcar-ba0ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK4s0qd04TBNIZUs8y0vA2lQA6w2VWb8g',
    appId: '1:260805929748:ios:47a0b2f2dc9ae4d2097001',
    messagingSenderId: '260805929748',
    projectId: 'rentalcar-ba0ca',
    storageBucket: 'rentalcar-ba0ca.appspot.com',
    iosBundleId: 'com.example.carrentalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK4s0qd04TBNIZUs8y0vA2lQA6w2VWb8g',
    appId: '1:260805929748:ios:47a0b2f2dc9ae4d2097001',
    messagingSenderId: '260805929748',
    projectId: 'rentalcar-ba0ca',
    storageBucket: 'rentalcar-ba0ca.appspot.com',
    iosBundleId: 'com.example.carrentalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcF2r_PFOX-FNq9FbOw2fZrp87fzoaeZI',
    appId: '1:260805929748:web:54e1a65ed7b278bf097001',
    messagingSenderId: '260805929748',
    projectId: 'rentalcar-ba0ca',
    authDomain: 'rentalcar-ba0ca.firebaseapp.com',
    storageBucket: 'rentalcar-ba0ca.appspot.com',
    measurementId: 'G-H6G26TE6FZ',
  );

}